/hppfs/work/pr28fi/di38jil/npb-shared/npb-lrz/npbench/benchmarks/nbody/nbody_numba_o.py:86: NumbaWarning: 
Compilation is falling back to object mode WITHOUT looplifting enabled because Function "nbody" failed type inference due to: Invalid use of type(CPUDispatcher(<function getAcc at 0x14b43a79f640>)) with parameters (array(float64, 2d, C), array(float64, 2d, C), float64, float64)

During: resolving callee type: type(CPUDispatcher(<function getAcc at 0x14b43a79f640>))
During: typing of call at /hppfs/work/pr28fi/di38jil/npb-shared/npb-lrz/npbench/benchmarks/nbody/nbody_numba_o.py (111)


File "../../../npbench/benchmarks/nbody/nbody_numba_o.py", line 111:
def nbody(mass, pos, vel, N, Nt, dt, G, softening):
    <source elided>
        # update accelerations
        acc = getAcc(pos, mass, G, softening)
        ^

  @nb.jit(nopython=False, forceobj=True, parallel=False, fastmath=True)
/hppfs/work/pr28fi/di38jil/npb-shared/npb-lrz/npbench/benchmarks/nbody/nbody_numba_op.py:86: NumbaWarning: 
Compilation is falling back to object mode WITHOUT looplifting enabled because Function "nbody" failed type inference due to: Invalid use of type(CPUDispatcher(<function getAcc at 0x14b43a79fd90>)) with parameters (array(float64, 2d, C), array(float64, 2d, C), float64, float64)

During: resolving callee type: type(CPUDispatcher(<function getAcc at 0x14b43a79fd90>))
During: typing of call at /hppfs/work/pr28fi/di38jil/npb-shared/npb-lrz/npbench/benchmarks/nbody/nbody_numba_op.py (112)


File "../../../npbench/benchmarks/nbody/nbody_numba_op.py", line 112:
def nbody(mass, pos, vel, N, Nt, dt, G, softening):
    <source elided>
        # update accelerations
        acc = getAcc(pos, mass, G, softening)
        ^

  @nb.jit(nopython=False, forceobj=True, parallel=True, fastmath=True)
WARNING: Compilation error, trying hard to find its origin...
Compilation error, trying hard to find its origin...
WARNING: Nope, I'm going to flood you with C++ errors!
Nope, I'm going to flood you with C++ errors!
CRITICAL: Cover me Jack. Jack? Jaaaaack!!!!
E: error: Command "/hppfs/work/pr28fi/di38jil/npb-shared/conda-npb/bin/x86_64-conda-linux-gnu-c++ -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /dss/dsshome1/07/di52vum/npb-shared/conda-npb/include -fPIC -O2 -isystem /dss/dsshome1/07/di52vum/npb-shared/conda-npb/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /hppfs/work/pr28fi/di38jil/npb-shared/conda-npb/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /hppfs/work/pr28fi/di38jil/npb-shared/conda-npb/include -fPIC -DENABLE_PYTHON_MODULE -D__PYTHRAN__=3 -DUSE_XSIMD -I/hppfs/work/pr28fi/di38jil/npb-shared/conda-npb/lib/python3.10/site-packages/pythran -I/dss/lrzsys/sys/spack/release/23.1.0/opt/skylake_avx512/openblas/0.3.23-intel-xwrnnjh/include -I/hppfs/work/pr28fi/di38jil/npb-shared/conda-npb/lib/python3.10/site-packages/numpy/core/include -I/dss/dsshome1/07/di52vum/npb-shared/conda-npb/include/python3.10 -c /hppfs/scratch/07/di52vum/tmp/tmp7wt4svxj.cpp -o /hppfs/scratch/07/di52vum/tmp/tmpysui4a4p/hppfs/scratch/07/di52vum/tmp/tmp7wt4svxj.o -std=c++11 -fno-math-errno -fvisibility=hidden -fno-wrapv -Wno-unused-function -Wno-int-in-bool-context -Wno-unknown-warning-option -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /hppfs/work/pr28fi/di38jil/npb-shared/conda-npb/include -fopenmp -march=native -ffast-math" failed with exit status 1
Cover me Jack. Jack? Jaaaaack!!!!
E: error: Command "/hppfs/work/pr28fi/di38jil/npb-shared/conda-npb/bin/x86_64-conda-linux-gnu-c++ -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /dss/dsshome1/07/di52vum/npb-shared/conda-npb/include -fPIC -O2 -isystem /dss/dsshome1/07/di52vum/npb-shared/conda-npb/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /hppfs/work/pr28fi/di38jil/npb-shared/conda-npb/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /hppfs/work/pr28fi/di38jil/npb-shared/conda-npb/include -fPIC -DENABLE_PYTHON_MODULE -D__PYTHRAN__=3 -DUSE_XSIMD -I/hppfs/work/pr28fi/di38jil/npb-shared/conda-npb/lib/python3.10/site-packages/pythran -I/dss/lrzsys/sys/spack/release/23.1.0/opt/skylake_avx512/openblas/0.3.23-intel-xwrnnjh/include -I/hppfs/work/pr28fi/di38jil/npb-shared/conda-npb/lib/python3.10/site-packages/numpy/core/include -I/dss/dsshome1/07/di52vum/npb-shared/conda-npb/include/python3.10 -c /hppfs/scratch/07/di52vum/tmp/tmp7wt4svxj.cpp -o /hppfs/scratch/07/di52vum/tmp/tmpysui4a4p/hppfs/scratch/07/di52vum/tmp/tmp7wt4svxj.o -std=c++11 -fno-math-errno -fvisibility=hidden -fno-wrapv -Wno-unused-function -Wno-int-in-bool-context -Wno-unknown-warning-option -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /hppfs/work/pr28fi/di38jil/npb-shared/conda-npb/include -fopenmp -march=native -ffast-math" failed with exit status 1
Traceback (most recent call last):
  File "/hppfs/work/pr28fi/di38jil/npb-shared//npb-lrz/run_benchmark.py", line 57, in <module>
    test.run(args["preset"], args["validate"], args["repeat"], args["timeout"])
  File "/hppfs/work/pr28fi/di38jil/npb-shared/npb-lrz/npbench/infrastructure/test.py", line 88, in run
    for impl, impl_name in self.frmwrk.implementations(self.bench):
  File "/hppfs/work/pr28fi/di38jil/npb-shared/npb-lrz/npbench/infrastructure/pythran_framework.py", line 45, in implementations
    raise (e)
  File "/hppfs/work/pr28fi/di38jil/npb-shared/npb-lrz/npbench/infrastructure/pythran_framework.py", line 40, in implementations
    foo = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1176, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: /hppfs/scratch/07/di52vum/tmp/tmpexzmzj69/nbody_pythran.so: cannot open shared object file: No such file or directory
srun: error: i01r03c03s12: task 0: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=3853190.59
